services:
  postgres:
    image: postgres:16-alpine
    container_name: it-blog-postgres
    environment:
      POSTGRES_DB: it_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
